config/routes.rb
Thejigsawapp::Application.routes.draw do
  

  get "topics/index"

  get "topics/new"

  get "topics/edit"

  get "topics/show"

  get "topics/delete"

  get "login/login"

  get "users/search"

  get "users/jigsaw"

  resources :logins
  
  resources :users do
    resources :games 
  end
  
  resources :games do
    resources :topics, :groups, :students
  end
  
  resources :jigsaws
  
  resources :groups do
    resources :students
  end
  
  resources :students 
  
  resources :documents
  
  get 'login', to: 'logins#new'
  
  root to: "logins#new" 
  
  get '/games/:id/del_docs', to: 'games#del_docs', as: 'game_del_docs'
  
  get '/student/:student_id/games/:id/play_game', to: 'games#play_game', as: 'student_game_play'
  
  get '/user/admin', to: 'users#admin', as: 'user_admin'
  
  
  
  
  

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    
    @game = Jigsaw.find(params[:game_id])
    @documents = @game.documents
    @user = User.find(@game.user)
    @document = Document.new
    @document.resource = @game
    
  end


  def edit
    
    @game = Jigsaw.find(params[:game_id])
    @document = Document.find(params[:id])
    
  end


  def show
    
    @game = Jigsaw.find(params[:game_id])
    @document = Document.find(params[:id])
    
  end


  def destroy
  
    @game = Jigsaw.find(params[:game_id])
    @document = Document.find(params[:id])
    @document.destroy

    redirect_to game_topics_path(@game), notice: 'Documento eliminado correctamente'
    
  end

  
  def create
    
    @game = Jigsaw.find(params[:game_id])
    @document = Document.new(params[:document])
      
    respond_to do |format|
      if @document.save
        format.html { redirect_to game_topics_url(@game), notice: 'Documento engadido correctamente' }
        format.json { render json: @jigsaw, status: :created, location: @jigsaw }
      else
        format.html { render action: "new" }
        format.json { render json: @jigsaw.errors, status: :unprocessable_entity }
      end
    end
      
  end
  
  
  def update
  
    @game = Jigsaw.find(params[:game_id])
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to edit_game_topic_url(@game, @document), notice: 'Documento gardado' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  
  end
  
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form_for_document.html.erb
<%= form_for @document, url: game_topic_path(@game, @document) do |f| %>

  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> evitaron a grabacion do documento:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="game_edit_form_label">
    <%= f.label :Nome, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :name, class: "game_edit_form_right_element" %>
  </div>
  <div class="game_edit_form_label">
    <%= f.label :Descrición, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :description, class: "game_edit_form_right_element" %>
  </div>
  <div class="game_edit_form_label">
    <%= f.label :URL, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :URL, class: "game_edit_form_right_element" %>
  </div>
  <div class="game_edit_form_label">
    <%= f.label :Tipo_de_recurso, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :resource_type, class: "game_edit_form_right_element" %>
  </div>
  <div class="game_edit_form_label">
    <%= f.label :ID_do_recurso, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :resource_id, class: "game_edit_form_right_element" %>
  </div>
  
  <div class="game_edit_form_button">
    <%= submit_tag 'Gardar documento' %>
  </div>
  
<% end %>

app/views/topics/_form_for_new_document.html.erb
<%= form_for @document, url: game_topics_path(@game) do |f| %>

  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> evitaron a grabacion do documento:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="game_edit_form_label">
    <%= f.label :Nome, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :name, class: "game_edit_form_right_element" %>
  </div>
  <div class="game_edit_form_label">
    <%= f.label :Descrición, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :description, class: "game_edit_form_right_element" %>
  </div>
  <div class="game_edit_form_label">
    <%= f.label :URL, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :URL, class: "game_edit_form_right_element" %>
  </div>
  <div class="game_edit_form_label">
    <%= f.label :Tipo_de_recurso, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :resource_type, class: "game_edit_form_right_element" %>
  </div>
  <div class="game_edit_form_label">
    <%= f.label :ID_do_recurso, class: "game_edit_form_left_element" %>
  </div>  
  <div class="game_edit_form_data">
    <%= f.text_field :resource_id, class: "game_edit_form_right_element" %>
  </div>
  
  <div class="game_edit_form_button">
    <%= submit_tag 'Engadir documento' %>
  </div>
  
<% end %>

app/views/topics/_table_for_documents.html.erb
<% if @documents.empty? %>

  <p>Non hai documentos neste xogo<br/>Engada algún dende o formulario da dereita</p>

<% else %>
	  
  <p><table class="game_edit_table">
		
    <tr>
	  <th width="20%" align="center">Nome</th>
	  <th width="40%" align="center">Descrición</th>
	  <th align="center">Opcións</th>
	</tr>
						
	<% @documents.each do |document| %>
	<tr>
	  <td width="20%" align="left"><%= document.name %></td>
	  <td width="40%" align="left"><%= document.description %></td>
	  <td align="center">
	  	<%= link_to 'Amosar', game_topic_path(@game, document) %>
	    <%= link_to 'Trocar', edit_game_topic_path(@game, document) %>
	    <%= link_to 'Eliminar', game_topic_path(@game, document), method: :delete, data: { confirm: 'Eliminar documento?' } %></td>
	</tr>
	<% end %>
	  
  </table></p>
	
  <p>
  	<%= link_to 'Eliminar todos', game_del_docs_path(@game), data: { confirm: 'Eliminar todos os documentos do xogo?' } %>
  </p>
  	
<% end %>

app/views/topics/edit.html.erb
<div class="game_edit_title">
	
  <h1>Configuración do xogo "<%= @game.title %>"</h1>
    
</div>

<div class="game_edit_info">
	
  <div class="game_edit_subtitle">
	<h2>Trocando documento "<%= @document.name %>"</h2>
	<p id="notice"><%= notice %></p>
  </div>
  <div class="game_edit_form">
    <%= render 'form_for_document' %>
  </div>

</div>

<div class="game_edit_options"> 
	
  <%= link_to 'Voltar', game_topics_path(@game) %> |
  <%= link_to 'Amosar', game_topic_path(@game, @document) %>
  
</div>

app/views/topics/index.html.erb
<div class="game_edit_title">
	
  <h1>Configuración do xogo "<%= @game.title %>"</h1>
   
</div>

<div align="center">
	
  <ul class="nav nav-tabs nav-justified">
    <li><%= link_to 'Datos', edit_game_path(@game) %></li>
    <li class="active"><%= link_to 'Documentos', game_topics_path(@game) %></li>
    <li><%= link_to 'Estudantes', game_groups_path(@game) %></li>
  </ul>

  
  <div class="game_edit_data">
  	
  	<div class="game_edit_subtitle">
	  <h2>Documentos engadidos ao xogo</h2>
	  <p id="notice"><%= notice %></p>
	</div>
	
  	<div class="game_edit_topics" align="center">
	  <%= render 'table_for_documents' %>
    </div>
	
	<div class="game_edit_topic_form"> 
		<%= render 'form_for_new_document' %>		 
	</div>
	
</div>
  	
</div>

<div class="game_edit_options"> 
	
	<%= link_to 'Rematar', user_games_path(@user) %> 

</div>

app/views/topics/show.html.erb
<div class="game_edit_title">
	
  <h1>Configuración do xogo "<%= @game.title %>"</h1>
  
</div>

<div class="game_edit_info">
	
  <div class="game_edit_subtitle">	
    <h2>Amosando documento "<%= @document.name %>"</h2>
    <p id="notice"><%= notice %></p>
  </div>
  
  <div class="game_edit_form">	
  
  <div class="game_edit_form_label">
    <b>Nome:</b>
  </div>
  <div class="game_edit_form_data">  
    <%= @document.name %>
  </div>
  
  <div class="game_edit_form_label">
    <b>Descrición:</b>
  </div>
  <div class="game_edit_form_data">  
    <%= @document.description %>
  </div>
  
  <div class="game_edit_form_label">
    <b>URL:</b>
  </div>
  <div class="game_edit_form_data">  
    <%= @document.URL %>
  </div>
  
  <div class="game_edit_form_label">
    <b>Tipo de recurso:</b>
  </div>
  <div class="game_edit_form_data">  
    <%= @document.resource_type %>
  </div>
  
  <div class="game_edit_form_label">
    <b>Denominación do recurso:</b>
  </div>
  <div class="game_edit_form_data">  
    <% if @document.resource_type == 'Jigsaw' %>
	  <%= @document.resource.title %>
	<% elsif @document.resource_type == 'User' %>
	  <%= @document.resource.name %>
	<% end %>    
  </div>
  
  </div>
  
</div>

<div class="game_edit_options"> 
	
  <%= link_to 'Voltar', game_topics_path(@game) %> |
  <%= link_to 'Trocar', edit_game_topic_path(@game, @document) %>

</div>