config/routes.rb
Thejigsawapp::Application.routes.draw do
  

  get "topics/index"

  get "topics/new"

  get "topics/edit"

  get "topics/show"

  get "topics/delete"

  get "login/login"

  get "users/search"

  get "users/jigsaw"

  resources :logins
  
  resources :users do
    resources :games 
  end
  
  resources :games do
    resources :topics, :groups, :students
  end
  
  resources :jigsaws
  
  resources :groups do
    resources :students
  end
  
  resources :students 
  
  resources :documents
  
  get 'login', to: 'logins#new'
  
  root to: "logins#new" 
  
  get '/games/:id/del_docs', to: 'games#del_docs', as: 'game_del_docs'
  
  get '/student/:student_id/games/:id/play_game', to: 'games#play_game', as: 'student_game_play'
  
  get '/user/admin', to: 'users#admin', as: 'user_admin'
  
  
  
  
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :jigsaw
  has_and_belongs_to_many :users
  attr_accessible :URL, :jigsaw_id
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  # games/:game_id/groups
  # listar grupos/estudantes dun xogo
  def index
    
    @game = Jigsaw.find(params[:game_id])
    @groups = @game.groups
    @user = User.find(@game.user)
    @users = User.where(:tipe => 2).page(params[:page]).per_page(10)
    @group = @groups.last
    @groups_count = 0
    @max_groups = 4
    @groups_countbis = 0
    
    @students = 0
    @number_of_students_error = 0
    @groups.each do |group|
      @students += group.users.count
      if @game.documents.count != group.users.count
        @number_of_students_error = 1
      end
    end
    
  end
  
  
  def create
    
    @game = Jigsaw.find(params[:jigsaw_id])
    @group = @game.groups.create(params[:group])

    redirect_to post_path(@game)
    
  end
  
  
  # groups/:id
  # eliminar grupo dun xogo
  def destroy
    
    @group = Group.find(params[:id])
    @game = @group.jigsaw
    
    @group.destroy

    redirect_to game_groups_path(@game), notice: 'Grupo eliminado correctamente' 
    
  end
  
  
  # game/:game_id/groups/:id/new
  # xerar grupo de xogo
  def new
    
    @game = Jigsaw.find(params[:game_id])
    @group = @game.groups.create()
    
    redirect_to game_groups_path(@game), notice: 'Grupo engadido correctamente'
    
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_info_for_students.html.erb
Seleccione estudantes na lista que se mostra a continuación para engadilos ao xogo que está configurando. O número de estudantes dun grupo está limitado polo número de documentos.

app/views/groups/_table_for_group.html.erb
<table class="game_edit_group_table">
	
  <tr>
    <th width="100%" align="center">Grupo <%= @groups_count %>	</th>
    <th><%= link_to @group, method: :delete, data: { confirm: 'Desexa desfacer o grupo?' } do %>
		  <img src="/assets/delete.jpeg" class="game_edit_group_delete_img">
		<% end %></th>
  </tr>

  <% @students.each do |student| %>
    <tr>
      <td width="75%" align="left"><%= student.name %></td>
      <td align="center">
      	<%= link_to 'Eliminar', group_student_path(@group, student), method: :delete, data: { confirm: 'Eliminar estudante do grupo?' } %></td>
    </tr>
  <% end %>

</table>

app/views/groups/_table_for_students.html.erb
<table class="game_edit_table">
	
  <tr>
    <th width="40%" align="center">Estudante</th>
    <th align="center">Engadir estudante ao...</th>
  </tr>

  <% @users.each do |user| %>
    <% @groups_countbis = 0 %>
    <tr>
      <td width="40%" align="left"><%= user.name %></td>
      <td align="center">
      	<%= link_to 'Xogo', edit_game_student_path(@game, user) %>
      	<% @groups.each do |group| %>
      	  <% @groups_countbis += 1 %>
      	  <% if group.users.count < @game.documents.count %>
      	    |
      	    <%= link_to edit_group_student_path(group, user) do %>
      	      Grupo <%= @groups_countbis %>	
      	    <% end %>
      	  <% end %>
      	<% end %>
     </td>
    </tr>
  <% end %>
  
</table>

<%= will_paginate @users %>

app/views/groups/index.html.erb
<div class="game_edit_title">
	
  <h1>Configuración do xogo "<%= @game.title %>"</h1>
  
</div>

<div align="center">

  <ul class="nav nav-tabs nav-justified">
    <li><%= link_to 'Datos', edit_game_path(@game) %></li>
    <li><%= link_to 'Documentos', game_topics_path(@game) %></li>
    <li class="active"><%= link_to 'Estudantes', game_groups_path(@game) %></li>
  </ul>

  <div class="game_edit_data">
  	
    <div class="game_edit_groups_info">	
  	  <p> <%= render 'info_for_students' %> </p>
  	  <p> Documentos configurados <b><%= @game.documents.count %></b> </p>
  	  <p> Número máximo de grupos <b><%= @max_groups %></b> </p>
  	  <% if (@students < @game.documents.count*@max_groups) %>	  		
  	  <p> <%= render 'table_for_students' %> </p>
  	  <% else %>
  	  <br />
  	  <br />
  	  <p class="green_text">Completou a configuración do xogo. <br /> Non se poden engadir máis estudantes.</p>
  	  <% end %>
    </div>
  
    <div class="game_edit_groups" align="center">
	
	<div class="game_edit_subtitle">
	  <h2>Estudantes do xogo</h2>
	  <p id="notice"><%= notice %></p>
	  <% if @number_of_students_error != 0 %>
	    <p class="red_text">Algún dos grupos ten un número incorrecto de estudantes. O número de estudantes dun grupo debe coincidir co número de documentos engadidos.</p>
	  <% end %>
    </div>
	
	<div class="game_edit_list_of_groups">
	<% if @groups.empty? %>
	  <p>Non hai grupos configurados</p>
	<% else %>  	
	  <% @groups.each do |group| %>
	
	    <% @group = group %>
	    <% @groups_count += 1 %>
	    <% @students = group.users %>
	
	  <div class="game_edit_group">
	  	<%= render 'table_for_group' %>
  	  </div>
	  
      <% end %>
    <% end %>
    </div>
    
    <div class="game_edit_group_new">
      <% if (@game.groups.count < @max_groups) %>
        <%= link_to 'Engadir grupo', new_game_group_path(@game) %>
      <% else %>
        Non se poden engadir máis grupos  
      <% end %>
    </div>
    
    </div>
  
  </div>
	  
</div>

<div class="game_edit_options"> 
  
  <%= link_to 'Rematar', user_games_path(@user)	 %>

</div>