config/routes.rb
Thejigsawapp::Application.routes.draw do
  

  get "topics/index"

  get "topics/new"

  get "topics/edit"

  get "topics/show"

  get "topics/delete"

  get "login/login"

  get "users/search"

  get "users/jigsaw"

  resources :logins
  
  resources :users do
    resources :games 
  end
  
  resources :games do
    resources :topics, :groups, :students
  end
  
  resources :jigsaws
  
  resources :groups do
    resources :students
  end
  
  resources :students 
  
  resources :documents
  
  get 'login', to: 'logins#new'
  
  root to: "logins#new" 
  
  get '/games/:id/del_docs', to: 'games#del_docs', as: 'game_del_docs'
  
  get '/student/:student_id/games/:id/play_game', to: 'games#play_game', as: 'student_game_play'
  
  get '/user/admin', to: 'users#admin', as: 'user_admin'
  
  
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :jigsaws, dependent: :destroy
  has_many :documents, as: :resource, dependent: :destroy
  has_and_belongs_to_many :groups
  
  attr_accessible :URL, :name, :surname1, :surname2, :photo, :email, :tipe, :class_group, :nick, :password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  http_basic_authenticate_with name: "root", password: "root", only: [:index]
  
    
  # GET /users
  # Lista de usuarios
  def index
    
    @users = User.page(params[:page]).per_page(14)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
    
  end


  # GET /users/:id/admin
  # Lista de opcións para administradores
  def admin
    
  end
  
  
  # GET /users/:id
  # Páxina principal de usuario
  def show
    
    @user = User.find(params[:id])
    @jigsaws = @user.jigsaws
    @groups = @user.groups
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
    
  end

  # GET /users/new
  # Engadir usuario á plataforma
  def new
    
    @user = User.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
    
  end


  # GET /users/1/edit
  # Editar información do usuario
  def edit
    
    @user = User.find(params[:id])
    
  end

  # POST /users
  # Engadir usuario á plataforma
  def create
    
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to new_user_path, notice: 'Usuario engadido correctamente' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PUT /users/1
  # Editar información do usuario
  def update
    
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to edit_user_path(@user), notice: 'Usuario gardado correctamente' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    
  end


  # DELETE /users/1
  # Eliminar usuario
  def destroy
    
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuario eliminado correctamente' }
      format.json { head :no_content }
    end
    
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> impediron a grabación na base de datos:</h2>
	  <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="label" >
    <%= f.label :Nome %>
  </div>  
  <div class="data">
    <%= f.text_field :name %>
  </div>
  <div class="label">
    <%= f.label :Primeiro_apelido %>
  </div>
  <div class="data">  
    <%= f.text_field :surname1 %>
  </div>
  <div class="label">
    <%= f.label :Segundo_apelido %>
  </div>
  <div class="data">  
    <%= f.text_field :surname2 %>
  </div>
  <div class="label">
    <%= f.label :Foto %>
  </div>
  <div class="data">  
    <%= f.text_field :photo %>
  </div>
  <div class="label">
    <%= f.label :Email %>
  </div>
  <div class="data">  
    <%= f.text_field :email %>
  </div>
  <div class="label">
    <%= f.label :Tipo %>
 </div>
  <div class="data">   
    <%= f.text_field :tipe %>
  </div>
  <div class="label">
    <%= f.label :Grupo %>
  </div>
   <div class="data">   
    <%= f.text_field :class_group %>
   </div>
  <div class="label">
    <%= f.label :Alias %>
  </div>
  <div class="data">  
    <%= f.text_field :nick %>
  </div>
  <div class="label">
    <%= f.label :Contrasinal %>
  </div>
  <div class="data">  
    <%= f.text_field :password %>
  </div>
  
  <br />
  
  <div class="button_for_form">
    <%= submit_tag 'Trocar datos' %>
  </div> 
  
<% end %>

app/views/users/_show_for_users.html.erb
  <p>
    <div class="etiqueta">
      <b>Nome:</b>
    </div>
    <div class="dato">  
      <%= @user.name %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Apelidos:</b>
    </div>
    <div class="dato">  
      <%= @user.surname1 %> <%= @user.surname2 %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Email:</b>
    </div>
    <div class="dato">  
      <%= @user.email %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Tipo:</b>
    </div>
    <div class="dato">
      <% if @user.tipe == 1 %>	  
        Mestre
      <% else %>
        Estudante
      <% end %>    
    </div>
  </p>
  <% if @user.tipe != 1 %>
  <p>
    <div class="etiqueta">
      <b>Clase:</b>
    </div>
    <div class="dato">  
      <%= @user.class_group %>
    </div>
  </p>
  <% end %>
  <p>
    <div class="etiqueta">
      <b>Alias:</b>
    </div>
    <div class="dato">  
      <%= @user.nick %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Contrasinal:</b>
    </div>
    <div class="dato">  
      <%= @user.password %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Xogos configurados:</b>
    </div>
    <div class="dato">  
      <%= @user.jigsaws.count %>
    </div>
  </p>
  <% if @user.tipe != 1 %>
  <p>
    <div class="etiqueta">
      <b>Documentos xerados:</b>
    </div>
    <div class="dato">  
      <%= @user.documents.count %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Xogos comezados:</b>
    </div>
    <div class="dato">  
      <%= @user.groups.count %>
    </div>
  </p>
  <% end %>

app/views/users/_table_for_jigsaws.html.erb
<div class="table_title">
	
  <h3>Xogos configurados</h3>
  	
</div>

<div class="table_data">

  <% if @jigsaws.count == 0 %>

  Non hai xogos configurados
  
  <% else %>

  <table class="borders">
	
    <tr>
      <th>Nome</th>
      <th>Opcións</th>
    </tr>
 
    <% @jigsaws.each do |jigsaw| %>
      <tr>
        <td><%= jigsaw.title %></td>
        <td><%= link_to 'Trocar', edit_user_jigsaw_path(jigsaw) %>
            <%= link_to 'Comezar/reanudar', user_jigsaw_path(@user) %>
            <%= link_to 'Eliminar', edit_user_jigsaw_path(jigsaw) %></td>
      </tr>
    <% end %>

  </table>

  <% end %>
  
</div>

app/views/users/admin.html.erb
<!-- <div class="admin_title">

  <h1>Administración da plataforma</h1>

  <p id="notice"><%= notice %></p>
  
</div>

<div class="admin_info" align="center">

  <p><%= link_to 'Control de accesos', logins_path %></p>
  <p><%= link_to 'Lista de usuarios', users_path %></p>
  <p><%= link_to 'Lista de xogos', jigsaws_path %></p>
  <p><%= link_to 'Lista de documentos', documents_path %></p>

</div>

<div class="admin_options"> 

  <%= link_to 'Saír', new_login_path %>

</div> -->

<header>

  <h1 align="center">Administración da plataforma</h1>

  <% if !notice.blank? %>
  <div align="center">
    <div class="well well-sm" style="max-width:250px">
      <p id="notice" align="center"><%= notice %></p>
    </div>
  </div>
  <% end %>
  
</header>

<section>

  <div align="center">	
    <div style="background-color:#FFFFFF;max-width:200px;margin-bottom:50px">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to 'Control de accesos', logins_path %></li><!-- class="active" -->
        <li><%= link_to 'Lista de usuarios', users_path %></li>
        <li><%= link_to 'Lista de xogos', jigsaws_path %></li>
        <li><%= link_to 'Lista de documentos', documents_path %></li>
      </ul>
    </div>
  </div>
  
</section>

<footer> 

  <div align="center">
    <%= link_to 'Saír', new_login_path %>
  </div>
  
</footer>

app/views/users/edit.html.erb
<div class="admin_title">

  <h1>Datos persoais de <%= @user.name %></h1>

  <p id="notice"><%= notice %></p>
  		
</div>

<div class="admin_info" align="center">

  <%= render 'form' %>

</div>

<div class="admin_options"> 

  <%= link_to 'Páxina principal', @user %>

</div> 

app/views/users/index.html.erb
<div class="admin_title">

  <h1>Lista de usuarios</h1>

  <p id="notice"><%= notice %></p>
  
</div>

<div class="admin_info" align="center">

  <table width="65%">
	
  <tr>
    <th width="15%" align="center">Nome</th>
    <th width="30%" align="center">Apelidos</th>
    <th width="10%" align="center">Grupo</th>
    <th width="10%" align="center">Tipo</th>
    <th align="center">Opcións</th>
  </tr>

  <% @users.each do |user| %>
  <tr>
    <td width="15%" align="center"><%= user.name %></td>
    <td width="30%" align="center"><%= user.surname1 %> <%= user.surname2 %></td>
    <td width="10%" align="center"><%= user.class_group %></td>
    <td width="10%" align="center">
    	<% if user.tipe == 1 %>Mestre
    	<% elsif user.tipe == 2 %>Estudante
    	<% else %>Error
    	<% end %></td>
    <td align="center">
    	<%= link_to 'Trocar', edit_user_path(user) %>
    	<%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Eliminar usuario?' } %>
    	| <%= link_to 'Acceder', user %>
    	</td>
  </tr>
  <% end %>

  </table>

  <%= will_paginate @users %>
  
</div>

<div class="admin_options"> 

  <%= link_to 'Novo usuario', new_user_path %> |
  <%= link_to 'Páxina principal', user_admin_path %>

</div>

app/views/users/new.html.erb
<div class="admin_title">

  <h1>Novo usuario</h1>

  <p id="notice"><%= notice %></p>
  		
</div>

<div class="admin_info" align="center">

  <%= render 'form' %>

</div>

<div class="admin_options"> 

  <%= link_to 'Lista de usuarios', users_path %>

</div>

app/views/users/show.html.erb
<div class="admin_title">

  <h1>Páxina principal de <%= @user.name %></h1>

  <p id="notice"><%= notice %></p>
  		
</div>

<div class="admin_info" align="center">
 	
 	<div class="user_show_image">
	  <%= link_to edit_user_path(@user) do %>
	    <img src="/assets/user_info.jpeg" class="user_show_image_properties">
	  <% end %>
	</div>
    <div class="user_show_explanation">
      <%= link_to edit_user_path(@user) do %>
        <p>Amosar/trocar os meus datos persoais</p>
	  <% end %>
	</div>
    
    <% if @user.tipe == 1 %>
 	  <div class="user_show_image">
	    <%= link_to user_games_path(@user) do %>
	      <img src="/assets/games.jpeg" class="user_show_image_properties">
	    <% end %>
	  </div>
      <div class="user_show_explanation">
        <%= link_to user_games_path(@user) do %>
          <p>Xestionar os meus xogos</p>
	    <% end %>
      </div>
    <% else %>
      <div class="user_show_image">
	    <%= link_to student_path(@user) do %>
	      <img src="/assets/games.jpeg" class="user_show_image_properties">
	    <% end %>
	  </div>
      <div class="user_show_explanation">
        <%= link_to student_path(@user) do %>
          <p>Acceder aos meus xogos</p>
	    <% end %>
      </div>
    <% end %>
    
</div>

<div class="admin_options"> 
	
  <%= link_to 'Saír', new_login_path %>
  
</div>