config/routes.rb
Thejigsawapp::Application.routes.draw do
  

  get "topics/index"

  get "topics/new"

  get "topics/edit"

  get "topics/show"

  get "topics/delete"

  get "login/login"

  get "users/search"

  get "users/jigsaw"

  resources :logins
  
  resources :users do
    resources :games 
  end
  
  resources :games do
    resources :topics, :groups, :students
  end
  
  resources :jigsaws
  
  resources :groups do
    resources :students
  end
  
  resources :students 
  
  resources :documents
  
  get 'login', to: 'logins#new'
  
  root to: "logins#new" 
  
  get '/games/:id/del_docs', to: 'games#del_docs', as: 'game_del_docs'
  
  get '/student/:student_id/games/:id/play_game', to: 'games#play_game', as: 'student_game_play'
  
  get '/user/admin', to: 'users#admin', as: 'user_admin'
  
  
  
  
  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    
    @user = User.find(params[:user_id])
    @games = @user.jigsaws

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Jigsaw.find(params[:id])
    @documents = @game.documents
    @groups = @game.groups
    @user = @game.user
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    
    @user = User.find(params[:user_id])
    @game = Jigsaw.new
    @game.user = @user
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    
    @game = Jigsaw.find(params[:id])
    @user = @game.user
    
  end

  # POST /games
  # POST /games.json
  def create
    
    @user = User.find(params[:user_id])
    @game = Jigsaw.new(params[:jigsaw])
        
    respond_to do |format|
      if @game.save
        format.html { redirect_to user_games_path(@user), notice: 'Xogo xerado correctamente' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Jigsaw.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:jigsaw])
        format.html { redirect_to edit_game_path(@game), notice: 'Xogo gardado correctamente' }
        format.json { head :no_content }
      else
        format.html { redirect_to edit_game_path(@game), notice: 'Errou a actualizacion do xogo' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # users/:user_id/games/:id
  # eliminar xogo dun usuario
  def destroy
    
    @user = User.find(params[:user_id])
    @game = Jigsaw.find(params[:id])
    
    @user.jigsaws.delete(@game)

    respond_to do |format|
      format.html { redirect_to user_games_path(@user), notice: 'Xogo eliminado' }
      format.json { head :no_content }
    end
    
  end
  
  
  def editdoc
    
  end
  
  
  def del_docs
    
    @game = Jigsaw.find(params[:id])
    @game.documents.clear
    
    redirect_to game_topics_path(@game), notice: 'Documentos eliminados'
    
  end
  
  
  # student/:id/games/:game_id
  # xogar a un determinado xogo
  def play_game
    
  end
  
  
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form_for_game.html.erb
<%= form_for @game, url: game_path(@game) do |f| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> evitaron gardar os datos:</h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group input-group-lg" style="padding-bottom:5px">
    <span class="input-group-addon" style="width:225px;text-align:right">Título</span>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="input-group input-group-lg" style="padding-bottom:5px">
    <span class="input-group-addon" style="width:225px;text-align:right">Descrición</span>
    <%= f.text_field :description, class:"form-control" %>
  </div>
  <div class="input-group input-group-lg" style="padding-bottom:5px">
    <span class="input-group-addon" style="width:225px;text-align:right">Foto</span>
    <%= f.text_field :photo, class:"form-control" %>
  </div>
  <div class="input-group input-group-lg" style="padding-bottom:5px">
    <span class="input-group-addon" style="width:225px;text-align:right">Fase</span>
    <%= f.text_field :phase, class:"form-control" %>
  </div>
  
  <%= fields_for @user do |user| %>
  	<div class="input-group input-group-lg" style="padding-top:10px">
      <span class="input-group-addon" style="width:225px;text-align:right">Nome do administrador</span>
      <%= user.text_field :nick, class:"form-control" %>
    </div>
  <% end %>
  
  <div class="game_edit_form_button">
    <%= f.submit "Gardar xogo" %>
  </div>  
  
<% end %>

app/views/games/_form_for_new.html.erb
<%= form_for @game, url: user_games_path(@user) do |f| %>

  <% if @game.errors.any? %>
    <div id="errors_from_form">
      <p class="errors"><%= pluralize(@game.errors.count, "erro") %> evitaron gardar os datos:
      <% @game.errors.full_messages.each do |msg| %>
          <br/><output >- <%= msg %></output>
      <% end %>
      </p>
    </div>
  <% end %>

  <div class="label">
    <%= f.label :Título %>
  </div>  
  <div class="data">
    <%= f.text_field :title %>
  </div>
  <div class="label_big">
    <%= f.label :Descrición %>
    </div>  
  <div class="data_big">
    <%= f.text_area :description, class: "admin_text_area" %>
  </div>
  <div class="label">
    <%= f.label :Foto %>
    </div>  
  <div class="data">
    <%= f.text_field :photo %>
  </div>
  <div class="label">
    <%= f.label :Fase %>
    </div>  
  <div class="data">
    <%= f.text_field :phase %>
  </div>
  
  <div class="label">
    <%= f.label :Administrador %>
    </div>  
  <div class="data">
    <%= f.text_field :user_id %>
  </div>
  
  <div class="botton_for_form">
    <%= f.submit "Gardar xogo", class: "" %>
  </div>  
  
<% end %>

app/views/games/_list_for_docs.html.erb
  <div class="game_docs">
		
    <h3>Documentos</h3>
	
	<% if @documents.empty? %>
	  Non hai documentos que amosar
	<% else %>
	  
		<% @documents.each do |document| %>
		
		<div class="game_doc">
		  <div class="game_doc_photo">
		    <img src="<%= document.URL %>" class="game_doc_photo_attributes" alt="No funciona">
		  </div>
		  <div class="game_doc_name">
			<p><%= document.name %></p>
			<p><%= document.description %></p>
		  </div>
		</div>
			
		<% end %>
	
	<% end %>
	
  </div>

app/views/games/_list_for_students.html.erb
  <div class="game_students">
		
	<h3>Estudantes</h3>
	
	<% if @groups.empty? %>
	  Non hai estudantes que amosar
	<% else %>
	
		<% @groups.each do |group| %>
		
		  <% @users = group.users %>
		  
		  <%= render 'list_for_users' %> 
			
		<% end %>

	<% end %>
	
  </div>

app/views/games/_show_for_games.html.erb
<div class="game_data">
	
  <div class="game_photo" align="right">
	<img class="game_photo_attributes" src="<%= @game.photo %>" alt="<%= @game.title %>">
  </div>
			  
  <div class="game_information">
		
	<div class="game_info_label">
	  <b>Título:</b>
	</div>
	<div class="game_info_data">  
	  <%= @game.title %>
	</div>
	<div class="game_info_label">
	  <b>Descrición:</b>
	</div>
	<div class="game_info_data">   
	  <%= @game.description %>
	</div>
	<div class="game_info_label">
	  <b>URL da foto:</b>
	</div>
	<div class="game_info_data">  
	  <%= @game.photo %>
	</div>
	<div class="game_info_label">
	  <b>Fase:</b>
	</div>
	<div class="game_info_data">  
	  <%= @game.phase %>
	</div>

  </div>

</div>

app/views/games/_show_for_users.html.erb
<div class="user_show_info_title">
  <h2>Datos persoais</h2>
</div>
			
<div class="user_show_info_photo" align="right">
  <img src="<%= @user.photo %>">
</div>
	  
<div class="user_show_info_data">
  <p>
    <div class="etiqueta">
      <b>Nome:</b>
    </div>
    <div class="dato">  
      <%= @user.name %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Apelidos:</b>
    </div>
    <div class="dato">  
      <%= @user.surname1 %> <%= @user.surname2 %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Email:</b>
    </div>
    <div class="dato">  
      <%= @user.email %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Tipo:</b>
    </div>
    <div class="dato">
      <% if @user.tipe == 1 %>	  
        Mestre
      <% else %>
        Estudante
      <% end %>    
    </div>
  </p>
  <% if @user.tipe != 1 %>
  <p>
    <div class="etiqueta">
      <b>Clase:</b>
    </div>
    <div class="dato">  
      <%= @user.class_group %>
    </div>
  </p>
  <% end %>
  <p>
    <div class="etiqueta">
      <b>Alias:</b>
    </div>
    <div class="dato">  
      <%= @user.nick %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Contrasinal:</b>
    </div>
    <div class="dato">  
      <%= @user.password %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Xogos configurados:</b>
    </div>
    <div class="dato">  
      <%= @user.jigsaws.count %>
    </div>
  </p>
  <% if @user.tipe != 1 %>
  <p>
    <div class="etiqueta">
      <b>Documentos xerados:</b>
    </div>
    <div class="dato">  
      <%= @user.documents.count %>
    </div>
  </p>
  <p>
    <div class="etiqueta">
      <b>Xogos comezados:</b>
    </div>
    <div class="dato">  
      <%= @user.groups.count %>
    </div>
  </p>
  <% end %>
</div>

app/views/games/_table_for_games.html.erb
<div class="table_games_title">
	
  <h2>Xogos configurados</h2>
  	
</div>

<div align="center" class="table_games_data">

  <% if @games.count == 0 %>

  Non hai xogos configurados
  
  <% else %>
  
  <table style="border:none">
	
    <!-- <tr>
      <th width="20%">Nome</th>
      <th width="50%">Descrición</th>
      <th>Opcións</th>
    </tr> -->
 
    <% @games.each do |game| %>
      <tr style="float:left">
        <td>
          <div class="panel panel-info">
			<div class="panel-heading">
			  <h3 class="panel-title"><%= game.title %></h3>
			</div>
			<div class="panel-body">
			  <img src="<%= game.photo %>" class="game_image_properties">	
			  <%= game.description %>
			</div>
			<div class="panel-footer">
			  <%= link_to 'Trocar', edit_game_path(game) %>
              <%= link_to 'Comezar/reanudar', game_path(game) %>
              <%= link_to 'Eliminar', user_game_path(@user, game), method: :delete, data: { confirm: 'Desexa eliminar o xogo?' } %>
            </div>
		  </div>
        </td>
      </tr>
    <% end %>
	
  </table>

  <% end %>
  
</div>

<div class="table_games_options">
	
  <%= link_to 'Novo xogo', new_user_game_path(@user) %>
  	
</div>	
	

app/views/games/_table_for_groups.html.erb
<div class="table_title">

  <h3>Xogos comezados</h3>

</div>

<div class="table_data">
	
  <% if @groups.count == 0 %>

  Non hai xogos comezados
  
  <% else %>

    <table class="borders">
	
      <tr>
        <th>Nome</th>
        <th>Fase</th>
      </tr>
 
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.jigsaw.title %></td>
        <td><%= group.jigsaw.phase %></td>
      </tr>
    <% end %>

    </table>

  <% end %>

</div>

app/views/games/edit.html.erb
<header>
	
  <h1>Configuración do xogo "<%= @game.title %>"</h1>
  <p id="notice"><%= notice %></p>
    
</header>

<section>
	
  <ul class="nav nav-tabs nav-justified">
    <li class="active"><%= link_to 'Datos', edit_game_path(@game) %></li>
    <li><%= link_to 'Documentos', game_topics_path(@game) %></li>
    <li><%= link_to 'Estudantes', game_groups_path(@game) %></li>
  </ul>

  <div align="center">	
	<div class="game_edit_subtitle">
	  <p><h2>Información xeral</h2></p>
	  <%= render 'form_for_game' %>
	</div>
  </div>
  
</section>

<footer> 
  
  <div align="center">	
    <%= link_to 'Rematar', user_games_path(@user) %>
  </div> 
   
</footer>

app/views/games/edit_doc.html.erb
<h1> edicion de documentos </h1>

app/views/games/index.html.erb
<header>
  <div>	
	<ol class="breadcrumb">
      <li><%= link_to 'Páxina principal', user_path(@user) %></li>
      <li class="active">Xogos</li>
    </ol>
  </div>
  <div align="center">	
    <h1>Xestión de xogos de <%= @user.name %></h1>
    <p id="notice"><%= notice %></p>
  </div>
</header>

<section>
  <div align="center">
    <%= render 'table_for_games'%>
  </div>
</section>

<footer> 
  <div align="center">	
    <%= link_to 'Páxina principal', user_path(@user) %>  
  </div>
</footer>

app/views/games/new.html.erb
<div class="title">
	
  <h1>Configuración de novo xogo</h1>

  <p id="notice"><%= notice %></p>
	
</div>

<div class="info">
	
  <%= render 'form_for_new' %>

</div>

<div class="options"> 
	
  <%= link_to 'Voltar', user_games_path(@user) %>

</div>

app/views/games/play_game.html.erb
<h1>Hello</h1>

app/views/games/show.html.erb
<div class="game_title">
	
	<h1>Información do xogo</h1>

	<p id="notice"><%= notice %></p>
	 
</div>
	
<div class="game_info">
	
	  <%= render 'show_for_games' %>
  	  	
      <%= render 'list_for_students' %>
	  
	  <%= render 'list_for_docs' %>
	  	  		
</div>

<div class="game_options"> 
	
	<%= link_to 'Voltar', user_games_path(@user) %>
	
</div>